### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by psuet** [BSpendlove/pykeadhcp#1]
Hi,

Great little and simple wrapper you got there. Thank you!

I would like to use your library for some project and add some features to it (support for Communication directly via Sockets for example), but unfortunately it does not post a license.

Could you please add a license to the project? MIT / BSD 3 / Apache seem pretty common for python libraries

**Comment by BSpendlove** [comment]
Hey, apologies sure thing! I will add the Apache!
